os:
  - linux
services:
  - docker
language: node_js
node_js:
  - '12.13.1'
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=12.13.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
    - MAVEN_USER_HOME=$HOME/.m2/repository/
before_install:
  - |
    if [[ $JHI_JDK = '8' ]]; then
      echo '*** Using OpenJDK 8'
    else
      echo '*** Using OpenJDK 11 by default'
      sudo add-apt-repository ppa:openjdk-r/ppa -y
      sudo apt-get update -q
      sudo apt-get install -y openjdk-11-jdk -y
      sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
      java -version
    fi
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fhvmaster_club-master
  - chmod +x mvnw
  - ./mvnw -ntp checkstyle:check
  - ./mvnw -ntp clean verify
  - ./mvnw -ntp com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments='run test' -Dmaven.repo.local=$MAVEN_USER_HOME
  - ./mvnw -ntp verify -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
addons:
  sonarcloud:
    organization: 'fhvmaster'
    token:
      secure: 'BGaar7ZbEPekS9xci82o6CVA/f2o6/1K1829WGZ+aHnA96vJlE/pq43kDlmLYBhBOGfnSN+kU3EYoBA9jqbSk9aU/+INi4qxxA9UmVwFwKh+YouNvo1UgtMMCzxyX6rN3OU0a6knMGG5QvjE6PWnxNgRrXVQw36Y0vGK4CDoGRnWzx88Q3OnaUbpV3mmhvDX4WKCUrWDHMbmefa69Erzu0anw/lXZFftDt2TNBwXShn5zZRwbfjQEkFvV/cpKCMLzIUWF7394IS7x9e95/zmzzEcRaEbQ3nsOgHbQBnzJjcho1IOsnaR6pYPghRc9jWH6CXfCxTYOf+ba1eP6HRiCsAjDMeeD6BH+DocfPGyx/WArRRN7yE/Ps3GlhzT0r392nUCtP+D/zCA8wgGYq5AJYU5Sw+RT57QZzKN/GizJlwsZD+6eMWkbaK0Y2OjJfYsezgUYQQ+YREpsz1AYHhAvL3I5PxdDnMI+IF8yAKoVYluMY86xCNEUIPmOoyXTHUCWtMq1S3wJH9ywiesXHIgiU2sgm1DGuf/NLbbRZghLssZNp9WT0JrharKYveYn9kCBe4DCCBJ3SsyrLv3RGCiEZQOfWaq5z9QD0udckNjDCt2TuxuZMdmeks8upuLAWe5qGkmGVcTH23q0GmyFZxPqZkhsExT6MTc8xyAbe69Qso='
  # encrypted value of your token
